scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.stairWest, function (sprite, location) {
    game.over(true)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestClosed, function (sprite, location) {
    game.showLongText("Uhhhhh The game is not done yet", DialogLayout.Bottom)
    game.showLongText("So the trencher is useless ._. - Never", DialogLayout.Bottom)
    pauseUntil(() => true)
})
game.showLongText("Made by Never (to prevent to steal the game by Claming to be Never -_-)", DialogLayout.Full)
let myMinimap = minimap.minimap()
info.setScore(0)
info.setLife(3)
game.setGameOverMessage(false, "You Lost :( Try Better this time")
game.setGameOverMessage(true, "You Won The Beta :D")
let mySprite = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    .......22...22......
    ......2322.2222.....
    ......232222222.....
    ......222222222.....
    .......22222b2......
    ........222b2.......
    .........222........
    ..........2.........
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 100, 100)
tiles.setTilemap(tilemap`Level1`)
tiles.placeOnRandomTile(mySprite, sprites.dungeon.collectibleInsignia)
scene.cameraFollowSprite(mySprite)
game.splash("Welcome To Beta of Heart Maze :D (Version 1.0)")
